server:
  port: 8761

eureka:
  client:
    register-with-eureka: false  # server does not register itself
    fetch-registry: false         # server does not fetch registry


spring:

  application:
    name: eureka



